pipeline:
  name: custom_test
  identifier: custom_test
  projectIdentifier: CIrepro
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: ss
        identifier: ss
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          pwd
                          ls
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
              - step:
                  type: Http
                  name: Http_1
                  identifier: Http_1
                  spec:
                    url: https://google.com
                    method: GET
                    headers:
                      - key: X-GitHub-Api-Version
                        value: "2022-11-28"
                    inputVariables: []
                    outputVariables: []
                  timeout: 10s
        tags: {}
