pipeline:
  name: delete2
  identifier: delete2
  projectIdentifier: CIrepro
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: ci
        identifier: ci
        template:
          templateRef: test
          versionLabel: v1
          gitBranch: main
          templateInputs:
            type: CI
            spec:
              execution:
                steps:
                  - step:
                      identifier: BuildAndPushDockerRegistry_1
                      type: BuildAndPushDockerRegistry
                      spec:
                        dockerfile: <+input>
                        context: <+input>
