pipeline:
  name: gitx-ci
  identifier: gitxci
  projectIdentifier: CIrepro
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.harnessgitconnector
        repoName: harness-docs-lijo
        build: <+input>
  stages:
    - stage:
        name: test1
        identifier: test1
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.harnessImage
                    image: nginx
                    shell: Sh
                    command: echo "testing"
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.k8sconnector1
              namespace: delete-lijo
              nodeSelector: {}
              os: Linux
