pipeline:
  name: test1
  identifier: test1
  projectIdentifier: cd_latest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: sd
        identifier: sd
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: pwd
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
